# Generated by Django 5.1.6 on 2025-04-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0006_rename_company_tourpackage_tourism_company_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourpackage',
            table='tourpackage',
        ),
    ]
