# Generated by Django 5.1.6 on 2025-04-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0012_alter_tourpackage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='tourism_company',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterModelTable(
            name='tourpackage',
            table=None,
        ),
        migrations.DeleteModel(
            name='TourismCompany',
        ),
    ]
