# Generated by Django 5.1.6 on 2025-04-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0014_tourismcompany_remove_tourpackage_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourpackage',
            table='tour_package',
        ),
    ]
