# Generated by Django 5.1.6 on 2025-04-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0017_alter_tourpackage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourpackage',
            table='TourPackage',
        ),
    ]
