# Generated by Django 5.1.6 on 2025-04-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0018_alter_tourpackage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourpackage',
            table=None,
        ),
    ]
