# Generated by Django 5.1.6 on 2025-04-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0022_alter_tourpackage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
