# Generated by Django 5.1.6 on 2025-04-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0023_alter_tourpackage_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourismCompany',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='tourpackage',
            table=None,
        ),
    ]
