# Generated by Django 5.1.6 on 2025-04-08 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0024_delete_tourismcompany_remove_tourpackage_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelTable(
            name='tourpackage',
            table='TourPackage',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour_package.tourismcompany'),
            preserve_default=False,
        ),
    ]
