# Generated by Django 5.1.6 on 2025-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0025_tourismcompany_alter_tourpackage_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='TourismCompany',
        ),
    ]
