# Generated by Django 5.1.6 on 2025-04-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_package', '0026_alter_tourpackage_company_delete_tourismcompany'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourpackage',
            table=None,
        ),
    ]
