# Generated by Django 5.1.6 on 2025-04-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0009_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
