# Generated by Django 5.1.6 on 2025-04-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0003_hotelroom_hotel_alter_hotelroom_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='rooms_available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
