# Generated by Django 5.1.6 on 2025-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0005_hotelbooking_latitude_hotelbooking_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
