# Generated by Django 5.1.6 on 2025-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0006_hotelroom_latitude_hotelroom_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
