# Generated by Django 5.1.6 on 2025-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0007_hotelbooking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelamenities',
            name='amenity',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('ac', 'Air Conditioning'), ('breakfast', 'Breakfast'), ('pool', 'Swimming Pool'), ('parking', 'Parking'), ('gym', 'Gym'), ('spa', 'Spa'), ('tv', 'Television'), ('minibar', 'Minibar')], max_length=100),
        ),
    ]
