# Generated by Django 5.1.6 on 2025-04-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0003_alter_guide_expertise'),
        ('bookings', '0006_alter_booking_table'),
        ('hotelbooking', '0006_hotelroom_latitude_hotelroom_longitude'),
        ('tour_package', '0014_tourismcompany_remove_tourpackage_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guides.guide'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.hotelbooking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour_package.tourpackage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='booking',
            table='Bookings',
        ),
    ]
